### ISSUE TITLE
If opencl not found revert to cpu

### ISSUE THREAD

**Issue by enetheru** [slowmoVideo/slowmoVideo#59]
I have successfully loaded slowmovideo and configured it for opencl.
I played with my driver situation and broke opencl functionality on my computer.
I cannot load slowmovideo because it expects opencl and closes.

**Comment by valgit** [comment]
can you post the crash logs ?

**Comment by enetheru** [comment]
```
enetheru@stark ~ $ slowmoUI 
threading info :  4 
("slowmoUI") 
check GPU 
CUDA support :  0 found 
OpenCL support 
OpenCV Error: Unknown error code -6 (OpenCL function is not available: [clGetPlatformIDs]) in opencl_check_fn, file /build/buildd/opencv-2.4.8+dfsg1/modules/ocl/src/cl_runtime/cl_runtime.cpp, line 83
end OpenCL support 
using OCL for OpenCV 
using OCL device :  0 for rendering 
Segmentation fault
```
```
(gdb) backtrace
#0  0x00000000004a23d8 in FlowSourceOpenCV_sV::initGPUDevice (this=0x824d30, dev=0)
    at /home/enetheru/git/slowmovideo/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:151
#1  0x0000000000482958 in Project_sV::reloadFlowSource (this=0x847090) at /home/enetheru/git/slowmovideo/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:155
#2  0x000000000048229e in Project_sV::init (this=0x847090) at /home/enetheru/git/slowmovideo/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:91
#3  0x0000000000482005 in Project_sV::Project_sV (this=0x847090) at /home/enetheru/git/slowmovideo/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:51
#4  0x000000000043efb2 in MainWindow::MainWindow (this=0x7fffffffdee0, projectPath=..., parent=0x0)
    at /home/enetheru/git/slowmovideo/slowmoVideo/src/slowmoVideo/slowmoUI/mainwindow.cpp:64
#5  0x000000000043dd37 in main (argc=1, argv=0x7fffffffe0e8) at /home/enetheru/git/slowmovideo/slowmoVideo/src/slowmoVideo/slowmoUI/main.cpp:83
```

**Comment by valgit** [comment]
for now, I don't know how to handle this case, as it appear to be in OpenCV libraries !
to bypass it quickly, you can modify the preferences outside of slowmovideoUI (under osx it's a plist, under windows it should be a registry, linux, i think it's a text file)

**Comment by valgit** [comment]
close by commit 93ce0d50f371b3715eba9126ad7a6e823d68c58d
